accounts/urls.py
from django.urls import path 
from .views import * 

urlpatterns = [
    path('register/', register_user, name='register'),
    path('login/', login_user, name='login'), 
    path('logout/', logout_user, name='logout')
]

dashboard/urls.py
from django.urls import path 
from .views import * 

urlpatterns = [
    path('', website, name='website'),
    path('dashboard/', dashboard, name='dashboard')
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('dashboard.urls')),               
    path('accounts/', include('accounts.urls')), 
    path('admin/', admin.site.urls),
    path('post/', include('post.urls'))
]

post/urls.py
from django.urls import path 
from .views import * 

urlpatterns = [
    path('create-category/', create_category, name='create-category'), 
    path('update-category/<str:title>/', update_category, name='update-category'), 
    path('create-post/', create_post, name='create-post'), 
    path('update-post/<slug:slug>/', update_post, name='update-post'), 
    path('all-categories/', all_categories, name='all-categories'), 
    path('all-posts/', all_posts, name='all-posts'), 
    path('post-details/<slug:slug>/', post_details, name='post-details'), 
]

accounts/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.contrib.auth import get_user_model
from ckeditor.fields import RichTextField


User = get_user_model()

class Category(models.Model):
    title = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.title

class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = RichTextField()
    is_published = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    likes = models.PositiveIntegerField(default=0)
    slug = models.SlugField(unique=True)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from .form import *

User = get_user_model()

def register_user(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'New account created. Please log in to continue')
            return redirect('login')
        else:
            messages.warning(request, 'Something went wrong. Please check form errors')
            return redirect('register')
    else:
        form = RegisterUserForm()
        context = {'form':form}
    return render(request, 'accounts/register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None and user.is_active:
            login(request, user)
            messages.success(request, 'Welcome! Enjoy and create amazing content')
            return redirect('dashboard')
        else:
            messages.warning(request, 'Something went wrong. Please check form errors')
            return redirect('login')
    return render(request, 'accounts/login.html')

def logout_user(request):
    logout(request)
    messages.success(request, 'We hope to see you back soon')
    return redirect('login')

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from post.models import Post

@login_required
def dashboard(request):
    context = {}
    return render(request, 'dashboard/dashboard.html', context)

def website(request):
    posts = Post.objects.filter(is_published=True)
    context = {'posts':posts}
    return render(request, 'dashboard/website.html', context)

post/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from .form import *
from .models import * 

def create_category(request):
    if request.method == 'POST':
        form = CreateCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'New category added')
            return redirect('all-categories')
        else:
            messages.warning(request, 'Something went wrong. Please check form errors')
            return redirect('all-categories')
    else:
        form = CreateCategoryForm()
        context = {'form':form}
    return render(request, 'post/create_category.html', context)

def update_category(request, title):
    category = Category.objects.get(title=title)
    if request.method == 'POST':
        form = UpdateCategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, 'Category information has been updated and saved')
            return redirect('all-categories')
            #return reverse("article_detail", args=[str(category.name)])
        else:
            messages.warning(request, 'Something went wrong. Please check form errors')
            return reverse("update-category", args=[str(category.title)])
    else:
        form = UpdateCategoryForm(instance=category)
        context = {'form':form}
    return render(request, 'post/update_category.html', context)

def create_post(request):
    if request.method == 'POST':
        form = CreatePostForm(request.POST)
        if form.is_valid():
            var = form.save(commit=False)
            var.author = request.user
            if not var.slug:
                var.slug = slugify(var.title)
            var.save()
            messages.success(request, 'New Post created.')
            return redirect('all-posts')
        else:
            messages.warning(request, 'Something went wrong. Please check form errors')
            return redirect('create-post')
    else:
        form = CreatePostForm()
        context = {'form':form}
    return render(request, 'post/create_post.html', context)

def update_post(request, slug):
    post = Post.objects.get(slug=slug)
    if request.method == 'POST':
        form = UpdatePostForm(request.POST, instance=post)
        if form.is_valid():
            var = form.save(commit=False)
            var.slug = slugify(var.title)
            var.save()
            messages.success(request, 'Post content has been updated and saved')
            return redirect('all-posts')
        else:
            messages.warning(request, 'Something went wrong. Please check form errors')
            return reverse("update-post", args=[str(post.slug)])
    else:
        form = UpdatePostForm(instance=post)
        context = {'form':form}
    return render(request, 'post/update_post.html', context)

def all_categories(request):
    categories = Category.objects.all()
    context = {'categories':categories}
    return render(request, 'post/all_categories.html', context)

def all_posts(request):
    posts = Post.objects.all()
    context = {'posts':posts}
    return render(request, 'post/all_posts.html', context)

def post_details(request, slug):
    post = Post.objects.get(slug=slug)
    context = {'post':post}
    return render(request, 'post/post_details.html', context)

templates/accounts/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Django Blog</title>
</head>

<body>

    <div class="container col-xl-10 col-xxl-8 px-4 py-5">
        <div class="row align-items-center g-lg-5 py-5">
            <div class="col-lg-7 text-center text-lg-start">
                <h1 class="display-4 fw-bold lh-1 mb-3">Create content with Django Blog</h1>
                <p class="col-lg-10 fs-4">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, est,
                    officia corrupti explicabo adipisci iste incidunt harum ipsam, blanditiis
                    dolores sed veritatis odit laborum! Saepe aut et repellat cum similique.
                </p>
            </div>
            <div class="col-md-10 mx-auto col-lg-5">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{message.tags}}" role="alert">
                    {{message}}
                </div>
                {% endfor %}
                {% endif %}

                {% block content %}
                {% endblock content %}

            </div>
        </div>
    </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block content %}

<form class="p-4 p-md-5 border rounded-3 bg-light" method='POST'>
    {% csrf_token %}
    <div class="form-floating mb-3">
        <input type="input" name="username" class="form-control" id="floatingInput">
        <label for="floatingInput">Username</label>
    </div>
    <div class="form-floating mb-3">
        <input type="password" name="password" class="form-control" id="floatingPassword">
        <label for="floatingPassword">Password</label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign In</button>
    <hr class="my-4">
    <!-- <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small> -->
    <small class="text-muted">Don't have an account? <a href="{% url 'register' %}">Sign Up</a></small>
</form>

{% endblock content %}

templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% load widget_tweaks %}

{% block content %}

<form class="p-4 p-md-5 border rounded-3 bg-light" method="POST">
    {% csrf_token %}
    <div class="form-floating mb-3">
        {% render_field form.username class="form-control" %}
        <label for="floatingInput">Username</label>
    </div>
    <div class="form-floating mb-3">
        {% render_field form.email class="form-control" %}
        <label for="floatingInput">Email ID</label>
    </div>
    <div class="form-floating mb-3">
        {% render_field form.password1 class="form-control" %}
        <label for="floatingInput">Enter Password</label>
    </div>
    <div class="form-floating mb-3">
        {% render_field form.password2 class="form-control" %}
        <label for="floatingInput">Confirm Password</label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign Up</button>
    <hr class="my-4">
    <!-- <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small> -->
    <small class="text-muted">Don't have an account? <a href="{% url 'login' %}">Sign In</a></small>
</form>

{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <i class="fa fa-cloud"></i> -->
    <script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
    <title>Django Blog</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Django Blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'dashboard' %}">Dashboard</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Posts
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'create-post' %}">Create Post</a></li>
                            <li><a class="dropdown-item" href="{% url 'all-posts' %}">View Posts</a></li>
                        
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Category
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'create-category' %}">Create Category</a></li>
                            <li><a class="dropdown-item" href="{% url 'all-categories' %}">View Categories</a></li>
                        </ul>
                    </li>
                    {% endif %}

                    <li class="nav-item">
                        {% if request.user.is_authenticated  %}
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">{{user.username}}</a>
                        {% else %}
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Guest User</a>
                        {% endif %}
                    </li>
                </ul>
                {% if request.user.is_authenticated %}
                <a href="{% url 'logout' %}" class="btn btn-warning btn-sm">Logout</a>
                {% else %}
                <a href="{% url 'login' %}" class="btn btn-warning btn-sm">Login</a>
                {% endif %}
                <!-- <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form> -->
            </div>
        </div>
    </nav>

    <div class="container mt-5">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}" role="alert">
            {{message}}
        </div>
        {% endfor %}
        {% endif %}
        
        {% block content %}
        {% endblock content %}

    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

templates/dashboard/dashboard.html
{% extends 'base.html' %}

{% block content %}

<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Welcome, {{request.user}}</h1>
        <p class="col-md-8 fs-4">Using a series of utilities, you can create this jumbotron, just like the one
            in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it
            to your liking.</p>
        <a href="{% url 'create-post' %}" class="btn btn-primary btn-lg" type="button">Create New Post</a>
    </div>
</div>

{% endblock content %}

templates/dashboard/website.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}

<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Welcome to Django Blog</h1>
        <p class="col-md-8 fs-4">Using a series of utilities, you can create this jumbotron, just like the one
            in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it
            to your liking.</p>
    </div>
</div>


<div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for post in posts %}
        <div class="col">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">{{post.title}}</h5>
                    <p class="card-text">{{post.description|safe|slice:"300"}} <a href="{% url 'post-details' post.slug %}">Read More</a></p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">Published {{post.date_created|naturaltime}}</small>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div> <br>
{% endblock content %}

templates/post/all_categories.html
{% extends 'base.html' %}

{% block content %}

<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Associated Post</th>
        </tr>
    </thead>
    <tbody>
        {% for category in categories %}
        <tr>
            <td>{{category.title}} <a href="{% url 'update-category' category.title %}"><i class="fa fa-pencil"></i></a>
            </td>
            <td>{{category.post_set.all.count}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

templates/post/all_posts.html
{% extends 'base.html' %}

{% block content %}

<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">Category</th>
            <th scope="col">Title</th>
            <th scope="col">Date Posted</th>
            <th scope="col">Likes Count</th>
            <th scope="col">Status</th>
        </tr>
    </thead>
    <tbody>
        {% for post in posts %}
        <tr>
            <td>{{post.category}}</td>
            <td>{{post.title}} <a href="{% url 'update-post' post.slug %}">
                <i class="fa fa-pencil"></i></a>
                <a href="{% url 'post-details' post.slug %}">
                    <i class="fa fa-eye"></i></a>
            </td>
            <td>{{post.date_created}}</td>
            <td>{{post.likes}}</td>
            {% if post.is_published %}
            <td><span class="badge bg-success">Published</span></td>
            {% else %}
            <td><span class="badge bg-warning">Draft</span></td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

templates/post/create_category.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}

<form class="p-4 p-md-5 border rounded-3 bg-light" method='POST'>
    {% csrf_token %}
    <div class="form-floating mb-3">
        {% render_field form.title class="form-control" %}
        <label for="floatingInput">Category Title</label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Submit</button>
</form>

{% endblock content %}

templates/post/create_post.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}

<form class="p-4 p-md-5 border rounded-3 bg-light" method='POST'>
    {% csrf_token %}
    <div class="form-floating mb-3">
        {% render_field form.category class="form-control" %}
        <label for="floatingInput">Category</label>
    </div>
    <div class="form-floating mb-3">
        {% render_field form.title class="form-control" %}
        <label for="floatingInput">Post Title</label>
    </div>
    <div class="form-floating mb-3">
        {% render_field form.description|add_class:"ckeditor" class="form-control" %}
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Submit</button>
</form>

{% endblock content %}

templates/post/post_details.html
{% extends 'base.html' %}

{% block content %}

<div class="p-5 mb-4 bg-light rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">{{post.title}}</h1>
        <p class="col-md-8 fs-4">By {{post.author}} | {{post.date_created}}</p>
    </div>
</div>

<div>
    {{post.description|safe}}
</div> <br>

{% endblock content %}

templates/post/update_category.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}

<form class="p-4 p-md-5 border rounded-3 bg-light" method='POST'>
    {% csrf_token %}
    <div class="form-floating mb-3">
        {% render_field form.title class="form-control" %}
        <label for="floatingInput">Category Title</label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Submit</button>
</form>

{% endblock content %}

templates/post/update_post.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}

<form class="p-4 p-md-5 border rounded-3 bg-light" method='POST'>
    {% csrf_token %}
    <div class="form-floating mb-3">
        {% render_field form.category class="form-control" %}
        <label for="floatingInput">Category</label>
    </div>
    <div class="form-floating mb-3">
        {% render_field form.title class="form-control" %}
        <label for="floatingInput">Post Title</label>
    </div>
    <div class="form-floating mb-3">
        {% render_field form.description|add_class:"ckeditor" class="form-control" %}
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Submit</button>
</form>

{% endblock content %}